### ISSUE TITLE
'EasyDict' object has no attribute 'urls'

### ISSUE THREAD

**Issue by thefeiter** [PhilippRigoll/osmapy#24]
```
Traceback (most recent call last):
  File "/home/marvin/.local/bin/osmapy", line 11, in <module>
    load_entry_point('osmapy', 'console_scripts', 'osmapy')()
  File "/home/marvin/apps/osmapy/osmapy/main.py", line 82, in main
    main_window = Main()
  File "/home/marvin/apps/osmapy/osmapy/main.py", line 51, in __init__
    self.viewer = Viewer.Viewer(self)
  File "/home/marvin/apps/osmapy/osmapy/Viewer/Viewer.py", line 27, in __init__
    self.tile_loaders.append(TileLoader.TileLoader(self, config_id))
  File "/home/marvin/apps/osmapy/osmapy/TileLoader/TileLoader.py", line 34, in __init__
    self.urls = config.slippy_tiles[config_id].urls
AttributeError: 'EasyDict' object has no attribute 'urls'
```

**Comment by thefeiter** [comment]
nervermind...

**Comment by thefeiter** [comment]
It was a typo in my config...
